blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a Question
    url: https://github.com/JourneyCodesAyush/josh/discussions
    about: Ask usage questions, request help, or start a discussion about JoSh (Journey Shell)
