name: "🐛 Bug Report"
description: "Report something that isn't working as expected"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug with **JoSh**! Please fill out this form so we can investigate and fix it faster.

  - type: input
    id: title
    attributes:
      label: Short Summary
      placeholder: "Terminal freezes when typing custom commands"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: |
        Please describe what you did, what happened, and what you expected to happen.
      description: |
        Screenshots, error logs, or console outputs are helpful. You can drag and drop images/files below.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open JoSh terminal
        2. Type `<your-custom-command>`
        3. Observe the freeze or issue
      description: Provide a list of steps to reproduce the bug.

  - type: input
    id: version
    attributes:
      label: JoSh Version
      placeholder: "v1.0.0"
      description: Please specify the version of JoSh you're using (if known).

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: "Google Chrome / Firefox / Safari"
      description: The browser in which the issue occurred.

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Windows 10 / macOS Ventura / Ubuntu 22.04"
      description: The operating system you're using.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I'm using the latest version of JoSh
        - label: I have checked the [Troubleshooting](../README.md#troubleshooting) section
        - label: I have included any relevant screenshots or logs
    validations:
      required: true
